---

- name: Copy default controlplane config
  copy:
    src: "{{ inventory_dir }}/clusters/{{ cluster_name }}/secrets/controlplane.yaml"
    dest: "{{ inventory_dir }}/clusters/{{ cluster_name }}/secrets/{{ inventory_hostname }}.yaml"
    force: true
  when: "'controlplane' in group_names"
  changed_when: false

- name: Copy default worker config
  copy:
    src: "{{ inventory_dir }}/clusters/{{ cluster_name }}/secrets/worker.yaml"
    dest: "{{ inventory_dir }}/clusters/{{ cluster_name }}/secrets/{{ inventory_hostname }}.yaml"
    force: true
  when: "'worker' in group_names"
  changed_when: false

- name: Create temporary patch directory
  run_once: true
  tempfile:
    state: directory
  register: patch_dir
  changed_when: false

- name: Copy patch templates
  template:
    src: "../patches/{{ item }}"
    dest: "{{ patch_dir.path }}/{{ inventory_hostname }}_{{ item }}"
  loop: "{{ patches }}"
  changed_when: false

- name: Apply patches
  shell: >
    talosctl machineconfig patch secrets/{{ inventory_hostname }}.yaml
    --patch @{{ patch_dir.path }}/{{ inventory_hostname }}_{{ item }}
    -o secrets/{{ inventory_hostname }}.yaml
  args:
    chdir: "{{ inventory_dir }}/clusters/{{ cluster_name }}"
  loop: "{{ patches }}"
  changed_when: false

- name: Copy local patch templates
  template:
    src: "{{ inventory_dir }}/patches/{{ item }}"
    dest: "{{ patch_dir.path }}/{{ inventory_hostname }}_{{ item }}"
  loop: "{{ local_patches }}"
  changed_when: false

- name: Apply local patches
  shell: >
    talosctl machineconfig patch secrets/{{ inventory_hostname }}.yaml
    --patch @{{ patch_dir.path }}/{{ inventory_hostname }}_{{ item }}
    -o secrets/{{ inventory_hostname }}.yaml
  args:
    chdir: "{{ inventory_dir }}/clusters/{{ cluster_name }}"
  loop: "{{ local_patches }}"
  changed_when: false
