---

- name: Set default secret list
  run_once: true
  set_fact:
    secrets: "{{ (groups['all'] + default_secrets) }}"
  vars:
    default_secrets:
      - secrets
      - controlplane
      - worker
      - talosconfig

- name: Create cluster dir
  run_once: true
  file:
    path: "../clusters/{{ cluster_name }}"
    state: directory
    mode: '0755'
  register: cluster_dir

- name: Create cluster dirs
  run_once: true
  file:
    path: "../clusters/{{ cluster_name }}/{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - secrets

- name: Get decrypted secrets stat
  run_once: true
  stat:
    path: "../clusters/{{ cluster_name }}/secrets/{{ item }}.yaml"
    checksum_algorithm: md5
  register: decrypted_stats
  loop: "{{ secrets }}"

- name: Get encrypted secrets stat
  run_once: true
  stat:
    path: "../clusters/{{ cluster_name }}/{{ item }}.yaml.enc"
    checksum_algorithm: md5
  register: encrypted_stats
  loop: "{{ secrets }}"

- name: Decrypt secret data
  run_once: true
  no_log: true
  shell: >
    ansible-vault decrypt "{{ item.item }}.yaml.enc"
    --output secrets/{{ item.item }}.yaml
    --vault-password-file ../../.vault_pass
    && md5sum secrets/{{ item.item }}.yaml
  args:
    chdir: ../clusters/{{ cluster_name }}
  vars:
    query: "results[?item=='{{ item.item }}'].stat.checksum"
  register: result
  loop: "{{encrypted_stats.results }}"
  when: item.stat.exists == true
  changed_when: >
    (decrypted_stats | json_query(query) | join()) == "" or
    (decrypted_stats | json_query(query) | join()) not in result.stdout
