---

- name: Get talos version
  shell: >
    talosctl version
    --talosconfig secrets/talosconfig.yaml
    -e {{ ip | regex_replace('/.+','')  }}
    -n {{ ip | regex_replace('/.+','')  }}
  register: talos_node_version_result
  changed_when: false
  args:
    chdir: ../clusters/{{ cluster_name }}
  when: upgrade_talos is defined and upgrade_talos == "true"

- name: Parse talos version
  set_fact:
    talos_node_version: "{{ talos_node_version_result.stdout  | regex_replace('\t','  ') | from_yaml }}"
  when: upgrade_talos is defined and upgrade_talos == "true"

- name: Print talos upgrade plan
  debug:
    msg: "Current: {{ talos_node_version.Server.Tag }} -> Upgrade: {{ talos_version }}"
  changed_when: talos_node_version.Server.Tag != talos_version
  when: upgrade_talos is defined and upgrade_talos == "true"

- name: Upgrade talos
  shell: >
    talosctl upgrade
    --talosconfig secrets/talosconfig.yaml
    -e {{ ip | regex_replace('/.+','')  }}
    -n {{ ip | regex_replace('/.+','')  }}
    --image ghcr.io/siderolabs/installer:{{ talos_version }}
    || sleep 60
  args:
    chdir: ../clusters/{{ cluster_name }}
  throttle: 1
  when:
    - upgrade_talos is defined and upgrade_talos == "true"
    - talos_node_version.Server.Tag != talos_version
